# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
#
---
- block:
      
  - name: INFLUX OVERLAY | configuring influxdb platform repo for CentOS / Redhat
    template:
      src: influxdb-repo.j2
      dest: /etc/yum.repos.d/influxdb.repo
      mode: 0644
    
  - name: INFLUX OVERLAY | installing {{ influxdb_version }}
    package:
      name: "{{ influxdb_version }}"
      state: present
    notify: yum-clean-all
        
  become: yes
  when:
     - got_root | default('yes')
     - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
