# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# configuration variables for telegraf services
telegraf:
  user: "{{ (got_root | default('yes')) | ternary('telegraf', ansible_user) }}"
  group: "{{ (got_root | default('yes')) | ternary('telegraf', ansible_user) }}"
  config_file: "{{ (got_root | default('yes')) | ternary('/etc/telegraf/telegraf.conf', (telegraf_config)) }}"
  service_name: telegraf
  config:
    logs: "{{ (got_root | default('yes')) | ternary('/var/log/telegraf/telegraf.log', (telegraf_log)) }}"
    output_format: json
    # files to monitor
    monitor:
      telegraf: "{{ (got_root | default('yes')) | ternary('/var/log/telegraf/telegraf.log', (telegraf_log)) }}"
      syslog: /var/log/messages
      broker: "{{ (got_root | default('yes')) | ternary('/var/log/kafka/server.log', (confluent_root + '/var/log/kafka/server.log')) }}"
    # must match the files being monitored
    pattern:
      telegraf: '^%{TIMESTAMP_ISO8601:timestamp:ts-rfc3339} %{TELEGRAF_LOG_LEVEL:level:tag}! %{GREEDYDATA:msg}'
      syslog: '%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}'
      broker: '\[%{TIMESTAMP_ISO8601:timestamp}\]%{SPACE}%{LOGLEVEL:level}%{SPACE}\[%{WORD}%{SPACE}%{DATA}\]%{SPACE}%{GREEDYDATA:message}'
    custom_pattern: 'TELEGRAF_LOG_LEVEL (?:[DIWE]+)'
  input_filters:
    agent:
      config:
        # precision: 1ns
        precision: 1s 
  output_filters:
    - kafka
kafkabroker:
  config:
    # if this gets changed it needs to be changed under kafka defaults
    port: '9092'
    sslPort: '9091'
